In [ ]:
import pandas as pd
import numpy as np

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [ ]:
iris = load_iris()
df = pd.DataFrame(
    iris.data,
    columns=iris.feature_names
)

In [ ]:
print(df.head())

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [ ]:
df["Species"] = iris.target_names[iris.target]

In [ ]:
print(df.head(10))

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2
5                5.4               3.9                1.7               0.4
6                4.6               3.4                1.4               0.3
7                5.0               3.4                1.5               0.2
8                4.4               2.9                1.4               0.2
9                4.9               3.1                1.5               0.1

  Species
0  setosa
1  setosa
2  setosa
3  setosa
4  setosa
5  setosa
6  setosa
7  setosa
8  setosa
9  setosa

In [ ]:
df.tail(10)

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),Species
140,6.7,3.1,5.6,2.4,virginica
141,6.9,3.1,5.1,2.3,virginica
142,5.8,2.7,5.1,1.9,virginica
143,6.8,3.2,5.9,2.3,virginica
144,6.7,3.3,5.7,2.5,virginica
145,6.7,3.0,5.2,2.3,virginica
146,6.3,2.5,5.0,1.9,virginica
147,6.5,3.0,5.2,2.0,virginica
148,6.2,3.4,5.4,2.3,virginica
149,5.9,3.0,5.1,1.8,virginica

In [ ]:
df.describe()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
count,150.000000,150.000000,150.000000,150.000000
mean,5.843333,3.057333,3.758000,1.199333
std,0.828066,0.435866,1.765298,0.762238
min,4.300000,2.000000,1.000000,0.100000
25%,5.100000,2.800000,1.600000,0.300000
50%,5.800000,3.000000,4.350000,1.300000
75%,6.400000,3.300000,5.100000,1.800000
max,7.900000,4.400000,6.900000,2.500000

In [ ]:
df.columns

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)', 'Species'],
      dtype='object')

In [ ]:
df.isnull().sum()

sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
Species              0
dtype: int64

In [ ]:
df.loc[3, "sepal length (cm)"] = np.nan
df.loc[7, "petal width (cm)"] = np.nan
df.loc[7, "sepal width (cm)"] = np.nan
df.loc[7, "petal length (cm)"] = np.nan
df.loc[7, "Species"] = np.nan

In [ ]:
df.isnull().sum()

sepal length (cm)    1
sepal width (cm)     1
petal length (cm)    1
petal width (cm)     1
Species              1
dtype: int64

In [ ]:
df.tail(10)

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),Species
140,6.7,3.1,5.6,2.4,virginica
141,6.9,3.1,5.1,2.3,virginica
142,5.8,2.7,5.1,1.9,virginica
143,6.8,3.2,5.9,2.3,virginica
144,6.7,3.3,5.7,2.5,virginica
145,6.7,3.0,5.2,2.3,virginica
146,6.3,2.5,5.0,1.9,virginica
147,6.5,3.0,5.2,2.0,virginica
148,6.2,3.4,5.4,2.3,virginica
149,5.9,3.0,5.1,1.8,virginica

In [ ]:
df = df.dropna(axis=1, how='all')

In [ ]:
df.tail()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),Species
145,6.7,3.0,5.2,2.3,virginica
146,6.3,2.5,5.0,1.9,virginica
147,6.5,3.0,5.2,2.0,virginica
148,6.2,3.4,5.4,2.3,virginica
149,5.9,3.0,5.1,1.8,virginica

In [ ]:
df.fillna(df.mean(numeric_only=True),inplace=True)

In [ ]:
df.isnull().sum()

sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
Species              1
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   Species            149 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [ ]:
df['Species'].unique()

array(['setosa', nan, 'versicolor', 'virginica'], dtype=object)

In [ ]:
df['sepal length (cm)'].unique()

array([5.1       , 4.9       , 4.7       , 5.85167785, 5.        ,
       5.4       , 4.6       , 4.4       , 4.8       , 4.3       ,
       5.8       , 5.7       , 5.2       , 5.5       , 4.5       ,
       5.3       , 7.        , 6.4       , 6.9       , 6.5       ,
       6.3       , 6.6       , 5.9       , 6.        , 6.1       ,
       5.6       , 6.7       , 6.2       , 6.8       , 7.1       ,
       7.6       , 7.3       , 7.2       , 7.7       , 7.4       ,
       7.9       ])

In [ ]:
# the target column can't be mean/max-filled like the numeric features,
# so any row still missing a Species label is dropped before encoding
df = df.dropna(subset=["Species"])

df.isnull().sum()

In [ ]:
encoder = LabelEncoder()

df["Species"] = encoder.fit_transform(df['Species'])

print(df.head())

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0           5.100000               3.5                1.4               0.2
1           4.900000               3.0                1.4               0.2
2           4.700000               3.2                1.3               0.2
3           5.851678               3.1                1.5               0.2
4           5.000000               3.6                1.4               0.2

   Species
0        0
1        0
2        0
3        0
4        0

In [ ]:
df.fillna(df.max(numeric_only=True),inplace=True)

In [ ]:
df['Species'].unique()

array([0, 3, 1, 2])

In [ ]:
from sklearn.model_selection import train_test_split

X = df.iloc[:, 0:4]
y = df["Species"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

In [ ]:
from sklearn import svm
from sklearn.metrics import accuracy_score

classifier = svm.SVC(kernel='linear')

classifier.fit(X_train, y_train)

SVC(kernel='linear')

In [ ]:
X_test_prediction = classifier.predict(X_test)

testing_data_accuracy = accuracy_score(X_test_prediction, y_test)

In [ ]:
print("Accuracy score of the testing data: ",testing_data_accuracy)

Accuracy score of the testing data:  1.0

In [ ]:
X_train_prediction = classifier.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, y_train)

print("Accuracy score of the training data: ", training_data_accuracy)

0.9666666666666667

## Detailed Model Evaluation

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix

print(classification_report(
    y_test,
    X_test_prediction,
    target_names=encoder.classes_
))

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

cm = confusion_matrix(y_test, X_test_prediction)

plt.figure(figsize=(6, 5))
sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    cmap="Blues",
    xticklabels=encoder.classes_,
    yticklabels=encoder.classes_
)
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.show()

## Try the Model on a Manual Input

In [ ]:
FEATURE_NAMES = list(X.columns)

print("Enter Iris Flower Information")
sepal_length = float(input("Sepal Length: "))
sepal_width = float(input("Sepal Width: "))
petal_length = float(input("Petal Length: "))
petal_width = float(input("Petal Width: "))

# create input dataframe (same column names/order the model was trained on)
input_data = pd.DataFrame(
    [[sepal_length, sepal_width, petal_length, petal_width]],
    columns=FEATURE_NAMES
)

# prediction
prediction = classifier.predict(input_data)
predicted_species = encoder.inverse_transform(prediction)

print(prediction, predicted_species)

## Save the Trained Model for Deployment

We persist the fitted classifier and the label encoder with `joblib` so the exact objects used here can be reloaded by a separate API process, without retraining.

In [ ]:
import joblib

joblib.dump(classifier, "iris_model.pkl")
joblib.dump(encoder, "label_encoder.pkl")

print("Saved: iris_model.pkl, label_encoder.pkl")

In [ ]:
import json

model_metadata = {
    "feature_names": list(X.columns),
    "target_names": list(encoder.classes_),
    "test_accuracy": float(testing_data_accuracy)
}

with open("model_metadata.json", "w") as f:
    json.dump(model_metadata, f, indent=2)

print(model_metadata)

## Create Deployment Files for Render

The cells below write out a small Flask API (`app.py`), its `requirements.txt`, and a `render.yaml` blueprint. These, together with `iris_model.pkl` and `label_encoder.pkl`, are everything Render needs to serve the model.

In [ ]:
%%writefile app.py
from flask import Flask, request, jsonify
import joblib
import pandas as pd

app = Flask(__name__)

classifier = joblib.load("iris_model.pkl")
encoder = joblib.load("label_encoder.pkl")

FEATURE_NAMES = [
    "sepal length (cm)",
    "sepal width (cm)",
    "petal length (cm)",
    "petal width (cm)"
]


@app.route("/", methods=["GET"])
def home():
    return jsonify({"message": "Iris classifier API is running"})


@app.route("/predict", methods=["POST"])
def predict():
    data = request.get_json()

    try:
        input_data = [[
            data["sepal_length"],
            data["sepal_width"],
            data["petal_length"],
            data["petal_width"]
        ]]
    except KeyError as e:
        return jsonify({"error": f"Missing field: {e}"}), 400

    input_df = pd.DataFrame(input_data, columns=FEATURE_NAMES)
    prediction = classifier.predict(input_df)
    species = encoder.inverse_transform(prediction)[0]

    return jsonify({"prediction": species})


if __name__ == "__main__":
    app.run(host="0.0.0.0", port=5000)

In [ ]:
%%writefile requirements.txt
flask
scikit-learn
numpy
pandas
joblib
gunicorn

In [ ]:
%%writefile render.yaml
services:
  - type: web
    name: iris-classifier-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app

In [ ]:
# bundle everything the API needs into one archive for easy download
!zip -r deployment_bundle.zip app.py requirements.txt render.yaml iris_model.pkl label_encoder.pkl model_metadata.json

## Deploying to Render

1. Push `app.py`, `requirements.txt`, `render.yaml`, `iris_model.pkl`, and `label_encoder.pkl` to a GitHub repository (or unzip `deployment_bundle.zip` into one).
2. On [Render](https://render.com), choose **New +  Web Service** and connect that repository.
3. Render reads `render.yaml` automatically and sets the build command to `pip install -r requirements.txt` and the start command to `gunicorn app:app`.
4. Once deployed, send a POST request to `https://<your-service>.onrender.com/predict` with a JSON body such as:

```json
{
  "sepal_length": 5.1,
  "sepal_width": 3.5,
  "petal_length": 1.4,
  "petal_width": 0.2
}
```